name: unit testing

on:
  push:
    branches:
    - main
    - master
    - dev
  pull_request:
    branches:
    - main
    - master
    - dev

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 21.7.1
      - name: Install Dependencies
        run: npm ci
      - name: Run Eslint
        run: npm run lint
      - name: Run Unit testing
        run: npm run test
